// Mocks generated by Mockito 5.1.0 from annotations
// in news_app_tdd_clean_arch/test/features/home/domain/use_cases/get_sports_news.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app_tdd_clean_arch/core/errors/failures.dart' as _i5;
import 'package:news_app_tdd_clean_arch/features/home/domain/entity/article.dart'
    as _i6;
import 'package:news_app_tdd_clean_arch/features/home/domain/respository/respository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i3.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Article>>> getSportsNews() =>
      (super.noSuchMethod(Invocation.method(#getSportsNews, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Article>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.Article>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Article>>>);
}
