// Mocks generated by Mockito 5.1.0 from annotations
// in news_app_tdd_clean_arch/test/features/home/presentation/bloc/home_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app_tdd_clean_arch/core/errors/failures.dart' as _i6;
import 'package:news_app_tdd_clean_arch/features/home/domain/entity/article.dart'
    as _i7;
import 'package:news_app_tdd_clean_arch/features/home/domain/respository/respository.dart'
    as _i2;
import 'package:news_app_tdd_clean_arch/features/home/domain/use_cases/get_sports_news.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeHomeRepository_0 extends _i1.Fake implements _i2.HomeRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetSportsNews].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSportsNews extends _i1.Mock implements _i4.GetSportsNews {
  MockGetSportsNews() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeHomeRepository_0()) as _i2.HomeRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Article>>> call() =>
      (super.noSuchMethod(Invocation.method(#call, []),
          returnValue: Future<_i3.Either<_i6.Failure, List<_i7.Article>>>.value(
              _FakeEither_1<_i6.Failure, List<_i7.Article>>())) as _i5
          .Future<_i3.Either<_i6.Failure, List<_i7.Article>>>);
}
